apiVersion: v1
kind: Template
metadata:
  name: grafanaTemplate
parameters:
- description: Namespace of Kafka Infra to Monitor
  name: KAFKA_CLUSTER_NAMESPACE
  value: ocp-kafka
  required: true
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: grafana-serviceaccount
    labels:
      app: strimzi
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: grafana-cluster-monitoring-binding
    labels:
      app: strimzi
  subjects:
    - kind: ServiceAccount
      name: grafana-serviceaccount
      namespace: ${KAFKA_CLUSTER_NAMESPACE}
  roleRef:
    kind: ClusterRole
    name: cluster-monitoring-view
    apiGroup: rbac.authorization.k8s.io