apiVersion: v1
kind: Template
metadata:
  name: grafanaTemplate
parameters:
- description: Token for Grafana SA
  name: SA_TOKEN
  required: true
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: grafana-config
  data: 
    grafana-datasource.yaml: |-
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
        access: proxy
        basicAuth: false
        withCredentials: false
        isDefault: true
        jsonData:
          timeInterval: 5s
          tlsSkipVerify: true
          httpHeaderName1: "Authorization"
        secureJsonData:
          httpHeaderValue1: "Bearer ${SA_TOKEN}" 
        editable: true
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: grafana
    labels:
      app: strimzi
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: grafana
    template:
      metadata:
        labels:
          name: grafana
      spec:
        serviceAccountName: grafana-serviceaccount
        containers:
        - name: grafana
          image: grafana/grafana:6.3.0
          ports:
          - name: grafana
            containerPort: 3000
            protocol: TCP
          volumeMounts:
          - name: grafana-data
            mountPath: /var/lib/grafana
          - name: grafana-logs
            mountPath: /var/log/grafana
          - name: grafana-config
            mountPath: /etc/grafana/provisioning/datasources/grafana-datasource.yaml
            readOnly: true
            subPath: grafana-datasource.yaml
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
        volumes:
        - name: grafana-data
          emptyDir: {}
        - name: grafana-logs
          emptyDir: {}
        - name: grafana-config
          configMap:
            name: grafana-config
- apiVersion: v1
  kind: Service
  metadata:
    name: grafana
    labels:
      app: strimzi
  spec:
    ports:
    - name: grafana
      port: 3000
      targetPort: 3000
      protocol: TCP
    selector:
      name: grafana
    type: ClusterIP
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: strimzi
    name: grafana
  spec:
    port:
      targetPort: grafana
    tls:
      termination: edge
    to:
      kind: Service
      name: grafana
      weight: 100
    wildcardPolicy: None