apiVersion: v1
kind: Template
metadata:
  name: logForwardingKafka
parameters:
- description: Kafka Bootstrap TLS Route
  name: KAFKA_BOOTSTRAP
  required: true
- description: Infra Logs Topic Name
  name: INFRA_TOPIC
  value: infra-logs-topic
- description: Audit Logs Topic Name
  name: AUDIT_TOPIC
  value: audit-logs-topic
- description: App Logs Topic Name
  name: APP_TOPIC
  value: app-logs-topic
objects:
- apiVersion: logging.openshift.io/v1
  kind: ClusterLogForwarder
  metadata:
    name: instance
    namespace: openshift-logging
  spec:
    outputs:
     - name: infra-topic
       type: kafka
       url: tls://${KAFKA_BOOTSTRAP}:443/${INFRA_TOPIC}
       secret:
         name: infra
     - name: audit-topic
       type: kafka
       url: tls://${KAFKA_BOOTSTRAP}:443/${AUDIT_TOPIC}
       secret:
         name: audit
     - name: app-topic
       type: kafka
       url: tls://${KAFKA_BOOTSTRAP}:443/${APP_TOPIC}
       secret:
         name: app
    pipelines:
     - name: infra-logs
       inputRefs:
       - infrastructure
       outputRefs:
       - infra-topic
       labels:
         logType: infra
     - name: audit-logs
       inputRefs:
        - audit
       outputRefs:
        - audit-topic
     - name: app-logs
       inputRefs:
        - application
       outputRefs:
        - app-topic
